services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finde-app
    volumes:
      - .:/var/www
    expose:
      - 9000
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: finde-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: finde-db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: finde_db
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
